### ISSUE TITLE
配置文件不合法

### ISSUE THREAD

**Issue by FanhuaAwA** [LUMOXu/Spit_chatBot#10]
启动qqbot.py之后提示配置文件不合法

**Comment by echothesky** [comment]
大概是bot json修改的时候没有注意格式，导致文件格式错误，建议使用编程软件打开再进行修改，或者在修改问json文件之后去网站https://jsonformatter.curiousconcept.com/#检查一下json文件格式是否有问题

**Comment by FanhuaAwA** [comment]
> 大概是bot json修改的时候没有注意格式，导致文件格式错误，建议使用编程软件打开再进行修改，或者在修改问json文件之后去网站 [https://jsonformatter.curiousconcept.com/#检查一下json文件格式是否有问题](https://jsonformatter.curiousconcept.com/#%E6%A3%80%E6%9F%A5%E4%B8%80%E4%B8%8Bjson%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%E6%98%AF%E5%90%A6%E6%9C%89%E9%97%AE%E9%A2%98)

不知道为什么 我重新替换了一下出问题的文件，他源文件这边就无法使用不知道为什么会这样 可以一共一份json吗 根目录的config.yml这个文件

**Comment by FanhuaAwA** [comment]
重新检测了一遍config.yam用编程软件打开搞了一下好了
