### ISSUE TITLE
三个奇怪的问题

### ISSUE THREAD

**Issue by q13007868130** [LUMOXu/Spit_chatBot#12]
有两个很奇怪的问题
第一个是每次回复会有几率在语句最前面加上，号或者你：（一下子就暴漏了身份
![SU7)CIRX9%1ZBJ82K%UB D](https://github.com/LUMOXu/Spit_chatBot/assets/70795949/6653b417-1bce-415b-b8f6-8ad13f530e68)
![A7LXUVKCQ $I`H~0~5V02$6](https://github.com/LUMOXu/Spit_chatBot/assets/70795949/0222f94b-b525-48a2-aec4-657c32077e14)
第二个是每次回复都会给主人发送一个API使用（感觉完全没有意义
![)}~95C$3STG671C 802BZ0](https://github.com/LUMOXu/Spit_chatBot/assets/70795949/c332b1fe-ea8a-4441-8961-8e423d820765)
还有个是指令识别的问题，因为群里有两个bot所以要用#触发指令。但是就会出现以下情况
![Z3)1NSP%S9M7CU$Q5KOZ0_W](https://github.com/LUMOXu/Spit_chatBot/assets/70795949/9a3058e9-f88c-4cf9-a3a7-186495b271fb)
这不就暴漏了嘛

**Comment by q13007868130** [comment]
还有个是指令识别的问题，因为群里有两个bot所以要用#触发指令。但是就会出现以下情况
![Z3)1NSP%S9M7CU$Q5KOZ0_W](https://github.com/LUMOXu/Spit_chatBot/assets/70795949/9a3058e9-f88c-4cf9-a3a7-186495b271fb)
这不就暴漏了嘛

**Comment by LUMOXu** [comment]
第一个：仔细看看issues，有解决思路。
第二个：这个统计消息功能好像出bug了，怀疑是pandas版本的问题，如果不想让bot发消息，可以把qqbot里update_msg_counter函数里的send_private_msg那行删掉。
第三个：之前有人问过我，之后他把解决方法放在视频的笔记里了，你可以看看。

**Comment by LUMOXu** [comment]
关于加逗号的问题，把配置文件里的reply_flag关掉

**Comment by q13007868130** [comment]
谢谢UP解答，我尝试加了这两行去除"你:"
            replies[0] = replies[0].replace(',', '').replace('你:', '')
            replies[0] = sender.strip() + ' ' + replies[0].strip() 
虽然开头会删掉，但是会留一个空格，第二行的方法也解决不了留一个空格的问题

**Comment by q13007868130** [comment]
不用了，自己解决了，谢谢UP
