### ISSUE TITLE
运行后显示缺少pycqBot模块

### ISSUE THREAD

**Issue by 15515151** [LUMOXu/Spit_chatBot#15]
C:\桌面\潜伏机器人\1\Spit_chatBot>qqbot.py
Traceback (most recent call last):
  File "C:\桌面\潜伏机器人\1\Spit_chatBot\qqbot.py", line 11, in <module>
    from pycqBot.cqApi import cqHttpApi, cqLog
ModuleNotFoundError: No module named 'pycqBot'
![QQ图片20230514170945](https://github.com/LUMOXu/Spit_chatBot/assets/79360869/08b756f6-d124-4daf-a8ed-2045cda90805)
也已添加了环境变量和运行了pip install pycqBot

**Comment by 15515151** [comment]
![QQ图片20230514171129](https://github.com/LUMOXu/Spit_chatBot/assets/79360869/f12efe4b-cec5-44b7-b506-d7d0b1f5919c)

**Comment by znxs** [comment]
我也是这种问题，不过pip下载了pycqbot之后就成了另一种问题了
![Snipaste_2023-05-16_19-40-36](https://github.com/LUMOXu/Spit_chatBot/assets/76854978/fc368a2f-ff2d-4af8-a424-9071d18052ef)
