### ISSUE TITLE
发送消息前面有的时候带给你：  有的时候又不带 不太明白

### ISSUE THREAD

**Issue by SliverKeigo** [LUMOXu/Spit_chatBot#25]
![image](https://github.com/LUMOXu/Spit_chatBot/assets/112426853/55f1e82d-4cd9-4622-a0ae-8191e3dea6d0)

**Comment by ARingKoishi** [comment]
看往期已经关闭的issue

**Comment by Stallion-X** [comment]
模型的随机性导致的，实在不舒服可以自己多加几条正则过滤掉
