### ISSUE TITLE
找不到包

### ISSUE THREAD

**Issue by huaCheng36** [LUMOXu/Spit_chatBot#4]
![QQ截图20230511003839](https://github.com/LUMOXu/Spit_chatBot/assets/77093208/211aafa5-40ed-4193-bd4b-38ceed9a3e21)

**Comment by StaceyXC** [comment]
这个可能是你安装的版本问题，你重新安一下文件夹里的requirement.txt写的版本试试

**Comment by LUMOXu** [comment]
pycqbot版本问题，直接pip就会出这个问题

**Comment by huaCheng36** [comment]
改成0.4.5.1版本了启动会乱码
![QQ截图20230511133101](https://github.com/LUMOXu/Spit_chatBot/assets/77093208/0f878f65-602f-463b-9ef5-909beeb1472b)

**Comment by LUMOXu** [comment]
把你文件夹里的那个go-cqhttp-xxxxxx.exe重命名成go-cqhttp.exe

**Comment by huaCheng36** [comment]
可以登录上了
这里是api问题还是端口问题
![QQ截图20230511134838](https://github.com/LUMOXu/Spit_chatBot/assets/77093208/b2956c93-5b4d-406b-bc14-8c15454dbc14)

**Comment by LUMOXu** [comment]
api，你的apikey似乎没钱了。
