### ISSUE TITLE
连接成功但bot无回复

### ISSUE THREAD

**Issue by echothesky** [LUMOXu/Spit_chatBot#9]
使用的是国外的windows server服务器搭建，已将chat.py与bot配置文件里的proxy字段相关代码全部注释，配置文件也填写完毕，运行结束之后出现如下图的情况，bot后台可以看到发给bot的消息，但bot不会回复，我无法判断这是否搭建成功，亦或者问题是出在go-cq还是qqbot，多有叨扰，但希望能得到大佬解答，谢谢
![YVE$ KX)4)}NR~G2K@TZAUS](https://github.com/LUMOXu/Spit_chatBot/assets/106248959/634cd900-44a8-460a-831b-b95ba39487ef)

**Comment by MoMorkIsGay** [comment]
你好，私聊不会回复，群聊消息才可以

**Comment by echothesky** [comment]
问题解决了，我自己的锅，qqbot需要建立两个通信，项目文件里自带的config.yml文件建立了两个通信连接，而我先入为主把原本的config.yml文件删除了让go-cq自己生成了一个，这导致就只有自己选择的一个通信连接

**Comment by echothesky** [comment]
> 你好，指令外的私聊不会回复，群聊消息才可以

很感谢大佬百忙抽空解答

**Comment by Kevin-free** [comment]
大佬们， 我也遇到类似情况，服务启动了，但是在群聊发送消息，后台没有接收和返回，请问怎么排查和解决？
<img width="882" alt="image" src="https://github.com/LUMOXu/Spit_chatBot/assets/26422757/579318cc-5c1a-404b-b5fc-4b05081fcaf1">
@echothesky
